name: experimental_workflow

on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Unique identifier for artifacts'
        required: false
        type: string

jobs:
  consume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Load ubuntu-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts/

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11.2'

      # trudag version 2025.7.23
      - name: Install trudag and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install git+https://gitlab.com/CodethinkLabs/trustable/trustable@cc6b72753e1202951d382f60ff08320f5a957c7b

      - name: Do shite
        run: |
          python3 TSF/scripts/experiment.py

      - name: Fetch data storage branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --all
          git checkout save_historical_data && git pull || git checkout -b save_historical_data
      
      - name: Load persistent data
        run: |
          if ! git ls-tree --name-only origin/save_historical_data TSF/TrustableScoring.db | grep TSF/TrustableScoring.db; then
            mkdir -p TSF
            touch TSF/TrustableScoring.db
            git add TSF/TrustableScoring.db
            git commit -m "Initialise persistent data storage"
            git push origin save_historical_data
          fi
          git checkout ${{ github.event.repository.default_branch }}
          git checkout save_historical_data -- TSF/TrustableScoring.db

      - name: Generate trudag report
        run: |
          trudag score --dump data_store
      
      - name: Checkout data storage branch
        run: |
          git stash push --include-untracked -- $(git status --porcelain | awk '{print $2}' | grep -v TSF/TrustableScoring.db)
          git checkout save_historical_data

      - name: Store persistent data
        run: |
          git add TSF/TrustableScoring.db
          git commit -m "Append data storage" || echo "Historical data already up to date."
          git push origin save_historical_data
      
      - name: Recover stash
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git stash apply
      
