name: experimental_workflow

on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Unique identifier for artifacts'
        required: false
        type: string

jobs:
  consume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts/
      - run: |
          echo "Using artifact:"
          ls -R artifacts
  moin:
    name: moin
    runs-on: ubuntu-latest
    steps:
      - name: moinsen
        run: python3 /TSF/experiment.py