name: experimental_workflow

on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Unique identifier for artifacts'
        required: false
        type: string

jobs:
  consume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Load ubuntu-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_id }}
          path: artifacts/
      
      - name: Process ubuntu-artifact
        run: |
          cd artifacts/
          mv ${{ inputs.artifact_id }}/* .
          rm -rf ${{ inputs.artifact_id }}
          ls -a
      
