name: Parent Workflow

on: 
  push: 
    branches:
      - main
      - experimental

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write
  security-events: write

jobs:

  ubuntu:
    name: Run Ubuntu Workflow
    uses: ./.github/workflows/ubuntu.yml
    with:
      artifact_id: "ubuntu-${{ github.sha }}"
      
  experimental_workflow:
    name: Run experimental workflow
    needs: [ubuntu]
    uses: ./.github/workflows/experimental_workflow.yml
    with:
      artifact_id: "ubuntu-${{ github.sha }}"


  collect_artifacts_non_pr:
    name: "Collect Results & Deploy"
    needs: [ubuntu]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ubuntu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check child workflow results 
        run: |
          echo "=== Checking Child Workflow Results ==="
          result="${{ needs[matrix.target].result }}"
          echo "${{ matrix.target }} workflow result: $result"

          if [[ "$result" != "success" ]]; then
            echo "❌ ${{ matrix.target }} workflow failed! Exiting..."
            exit 1
          fi
          echo "✅ Child workflows completed successfully!" 
        env:
          current_workflow: ${{ matrix.target }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: "${{ matrix.target }}-${{ github.sha }}"
          path: artifacts/
